#!/bin/bash
#
#    Copyright (C) 2006  Brian Brazil
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

CONTENT_DIR=$PWD/example-content
IMGDIR=$PWD/images
rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source example-content$VERSION
apt-get --yes build-dep example-content$VERSION
cd example-content-*

sed -i "s/Ubuntu/$DISTRONAME/" debian/rules
sed -i "s/Ubuntu/$DISTRONAME/; /http/d" debian/control

# Stuff that's Ubuntu specific
rm -fr *buntu* case* logos/*.png
rm -f oo-about-these-files.odt oo-cd-cover.odg oo-derivatives.doc oo-welcome.odt

cp $CONTENT_DIR/* .

# If the custom icon exists
if [ -f $IMGDIR/$DISTRONAME_L-icon-48x48.png ]; then
	# Copy it into the logos directory
	cp $IMGDIR/$DISTRONAME_L-icon-48x48.png logos/
else
	# Otherwise remove it from debian/rules so there will be no logos/ dir
	sed -i -e 's/cp -p logos/# cp -p logos/g' debian/rules
fi

echo | dch -D $RELEASE -v $(sed -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${EXAMPLE_CONTENT_VERSION}'#p' debian/changelog)  "Changed to reflect $RELEASE"

dpkg-buildpackage $DPKGOPTS
