#!/bin/bash
#
#    Copyright (C) 2006  Brian Brazil
#    Copyright (C) 2011  Sam Geeraerts
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source psutils$VERSION
rm *.orig.*
apt-get --yes build-dep psutils$VERSION
cd psutils-*

rm Makefile.*

for file in md68_0.ps md71_0.ps ; do
	rm "$file"
	sed -i s/"$file"//g Makefile
	sed -i s/"$file"//g debian/patches/showchar-manpage.diff
	sed -i /"$file"/d README
done

rm fixmacps.man
rm fixmacps.pl
sed -i '/^fixmacps:/,+3d' Makefile
sed -i '/^fixmacps\.\$(MANEXT)/,+2d' Makefile
sed -i 's/fixmacps\.\$(MANEXT) //' Makefile
sed -i 's/fixmacps //' Makefile

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${PSUTILS_VERSION}'#p' debian/changelog)  "Remove non-free Postscript files."

dpkg-buildpackage $DPKGOPTS
