#!/bin/bash
#
#    Copyright (C) 2006  Brian Brazil
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source app-install-data-ubuntu$VERSION
apt-get --yes build-dep app-install-data-ubuntu$VERSION
cd app-install-data-ubuntu*

egrep -lr 'X-AppInstall-Section=(multiverse|restricted)' . | xargs -r rm
# Let's not confuse people
rm -f ./menu-data/{firefox{,-2},vlc}.desktop

# Fix proprietary apps being left in menus (ref https://bugs.launchpad.net/ubuntu/+source/app-install-data-commercial/+bug/410975 )
if [ `grep -c 'update-app-install' debian/postinst` -eq 0 ]; then
	echo -e "\nupdate-app-install || true\n" >> debian/postinst
fi

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${APP_INSTALL_DATA_UBUNTU_VERSION}'#p' debian/changelog) "Removed multiverse packages."

dpkg-buildpackage $DPKGOPTS
