#!/bin/bash
#
#    Copyright (C) 2006 Yoni Rabkin
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source module-init-tools$VERSION
apt-get --yes build-dep module-init-tools$VERSION
cd module-init-tools-*

sed -i "/^blacklist eepro100/d" extra/modprobe.d/blacklist

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${MODULE_INIT_TOOLS_VERSION}'#p' debian/changelog)  "Removed eepro100 from blacklist."

dpkg-buildpackage $DPKGOPTS
