#!/bin/bash
#
#    Copyright (C) 2009  Karl Goetz
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

IMGDIR=$PWD/images
rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source texlive-base
apt-get --yes build-dep texlive-base
cd texlive-base-*

cp $IMGDIR/texlive-base-00LICENCE debian/00LICENCE-UPDATED

if [ `grep -c 00LICENCE-UPDATED debian/rules` -eq 0 ]; then
	sed -i 's#dh_installdocs -A debian/README.Debian-source#dh_installdocs -A debian/README.Debian-source\n\tdh_installdocs -p texlive-common debian/00LICENCE-UPDATED#' debian/rules
fi


echo | dch -D $RELEASE -v $(sed -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${TEXLIVE_BASE_VERSION}'#p' debian/changelog)  'Inserted new licence file'

dpkg-buildpackage $DPKGOPTS

