#!/bin/bash
#
#    Copyright (C) 2010  Sam Geeraerts
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source xchat$VERSION
apt-get --yes build-dep xchat$VERSION
cd xchat-*

sed -i '/static char defaultconf_urlhandlers\[\] =/{N;s#"NAME Open Link in Opera.*CMD !opera.*"#"" ""#g;}' \
src/common/xchat.c

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${XCHAT_VERSION}'#p' debian/changelog)  "Don't refer to a non-free browser."

dpkg-buildpackage $DPKGOPTS
