#!/bin/bash
#
#    Copyright (C) 2009  Andrew Wigglesworth
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source vlc$VERSION
rm *.orig.*
cd vlc-*

# Non-free file to remove
rm modules/stream_out/transrate/putvlc.h

# Edit debian/control to depend on the (older) automake required.
sed -i -e  's/automake/automake1.9/' debian/control

# Install build dependencies.
apt-get --yes build-dep vlc$VERSION
apt-get install automake1.9

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${VLC_VERSION}'#p' debian/changelog)  "Changed to remove non-free file"

# dpkg-buildpackage --ignore=missing $DPKGOPTS
dpkg-buildpackage $DPKGOPTS
