#!/bin/bash
#
#    Copyright (C) 2006  Brian Brazil
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

IMGDIR=$PWD/images
rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source human-icon-theme$VERSION
apt-get --yes build-dep human-icon-theme$VERSION
cd human-icon-theme-*

# CC-BY-SA doesn't belong in non-free.
sed -i -e "s#Section: non-free/x11#Section: x11#g" debian/control.in

# Icons
if [ -f $IMGDIR/$DISTRONAME_L-icon-48x48.png ]; then
	cp $IMGDIR/$DISTRONAME_L-icon-48x48.png 48x48/places/start-here.png
else
	convert -size 48x48 xc:transparent -fill $LOGO_COLOUR -gravity Center -pointsize 44 -draw "text 0,-4 '$LOGO_LETTER'" 48x48/places/start-here.png
fi

if [ -f $IMGDIR/$DISTRONAME_L-icon-24x24.png ]; then
	cp $IMGDIR/$DISTRONAME_L-icon-24x24.png 24x24/places/start-here.png
else
	convert -size 24x24 xc:transparent -fill $LOGO_COLOUR -gravity Center -pointsize 20 -draw "text 0,-2 '$LOGO_LETTER'" 24x24/places/start-here.png
fi

if [ -f $IMGDIR/$DISTRONAME_L-icon-22x22.png ]; then
	cp $IMGDIR/$DISTRONAME_L-icon-22x22.png 22x22/places/start-here.png
else
	convert -size 22x22 xc:transparent -fill $LOGO_COLOUR -gravity Center -pointsize 18 -draw "text 0,-2 '$LOGO_LETTER'" 22x22/places/start-here.png
fi

if [ -f $IMGDIR/svg/$DISTRONAME_L.svg ]; then
	cp $IMGDIR/svg/$DISTRONAME_L.svg scalable/places/start-here.svg
else
	convert -size 48x48 xc:transparent -fill $LOGO_COLOUR -gravity Center -pointsize 44 -draw "text 0,-4 '$LOGO_LETTER'" ./scalable/places/start-here.svg
fi

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${HUMAN_ICON_THEME_VERSION}'#p' debian/changelog)  "Munged to show $DISTRONAME graphics"

dpkg-buildpackage $DPKGOPTS
