#!/bin/bash
#
#    Copyright (C) 2012  Sam Geeraerts
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

rm -rf $WORKINGDIR
mkdir -p $WORKINGDIR
cd $WORKINGDIR

apt-get source bogofilter$VERSION
rm *.orig.*
apt-get --yes build-dep bogofilter$VERSION
cd bogofilter-*

rm doc/bogofilter-SA-2005-01
rm doc/bogofilter-SA-2005-02

echo | dch -D $RELEASE -v $(sed  -n '1s#^.*(\(.*\)).*#\1'${DISTRONAME_L}${BOGOFILTER_VERSION}'#p' debian/changelog) "Removed non-free documentation."

dpkg-buildpackage $DPKGOPTS
