#!/bin/bash
#
#    Copyright (C) 2006  Brian Brazil
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#

# Pushes the repo to the mirror


. config


date '+%s%n%c' > $REPODST/dists/.last_push_repo
date '+%s%n%c' > $REPODST/cdimage/.last_push_repo
rsync -va $RSYNC_OPTIONS $REPODST/pool $RSYNC_DEST/$DISTRONAME_L/
rsync -va $RSYNC_OPTIONS --delete $REPODST/dists $RSYNC_DEST/$DISTRONAME_L/
# Can only delete after dists is updated
rsync -va --delete --delete-excluded $RSYNC_OPTIONS $REPODST/pool $RSYNC_DEST/$DISTRONAME_L/
rsync -va $RSYNC_OPTIONS $REPODST/cdimage/.last_push_repo $RSYNC_DEST/cdimage/.last_push_repo

