#!/bin/bash
#
#    Copyright (C) 2008  Brian Brazil
#    Copyright (C) 2010  Sam Geeraerts
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#


. config

# -security etc.
VARIANT=$1

DIR=$WORKINGDIR/$MIRRORDIST$VARIANT-$GNS_HOST_ARCH

if ! [ -f $DIR/bootstrap-done ]; then
	rm -rf $DIR
	mkdir -p $DIR

	debootstrap --arch=$GNS_HOST_ARCH $MIRRORDIST $DIR $MIRROR

	touch $DIR/bootstrap-done
fi

cat > $DIR/etc/apt/sources.list <<EOF
deb $MIRROR $MIRRORDIST main universe
deb-src $MIRROR $MIRRORDIST main universe
EOF

if [ -n "$VARIANT" ];then
	cat >> $DIR/etc/apt/sources.list <<EOF
deb $MIRROR $MIRRORDIST$VARIANT main universe
deb-src $MIRROR $MIRRORDIST$VARIANT main universe
EOF
fi

# Name chroot in /etc/debian_chroot 
echo -e "$MIRRORDIST-CHROOT$VARIANT-$GNS_HOST_ARCH" > $DIR/etc/debian_chroot

# Copy primary systems hosts file into chroot
cp /etc/hosts $DIR/etc/hosts

# Copy of builder for use in chroot.
# Copy with hardlinking when chroot is on same filesystem.
if [ "$(stat --format=%d .)" = "$(stat --format=%d $DIR)" ] ; then
	cp -afl . "$DIR"/builder || true
fi
# Always rsync to either delete old stuff or copy across filesystems.
rsync -ra --delete . $DIR/builder

if ! mountpoint $DIR/proc; then
	mount proc -t proc $DIR/proc
fi

chroot $DIR bash -c "set -ex; DEBIAN_PRIORITY=critical apt-get -y update && apt-get -y dist-upgrade && 
apt-get -y install build-essential kernel-wedge imagemagick netpbm fakeroot sharutils devscripts unifdef equivs $CHROOT_EXTRA_PACKAGES && 
/builder/fixup-kernel-wedge"
