#!/bin/bash
#
#    Copyright (C) 2010  Sam Geeraerts
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301 USA
#
# This script removes everything (source, dsc, binaries) of a source package
# from the package pool.

if [ $# -ne 1 ] ; then
  echo "Usage: $(basename $0) <source package name>"
  exit 1
fi

pkg=$1

cd `dirname $0`/..
. config

for postfix in '' -security $EXTRAS ; do
  reprepro -Vb $REPODST removesrc $RELEASE$postfix $pkg
done

